import { IpVersion, NumericValueType } from "@rxweb/reactive-form-validators";
import { PasswordValidation } from "@rxweb/reactive-form-validators/models";

export class FormBuilderData {
    public static GetValidators() {
        return Object.assign({},...[
            {"allOf": [{ "message": "string" }, { "conditionalExpression": "string" }, { "matchValues": "any[]" }]},
            { "alpha": [{ "message": "string" }, { "conditionalExpression": "string" }, { allowWhiteSpace: "boolean" }] },
            { "alphaNumeric": [{ "message": "string" }, { "conditionalExpression": "string" }, { allowWhiteSpace: "boolean" }] },
            { "ascii": [{ "message": "string" }, { "conditionalExpression": "string" }] },
            { "choice": [{ "minLength": "number" }, { "maxLength": "number" }, { "message": "string" }, { "conditionalExpression": "string" }] },
            { "compare": [{ "fieldName": "string" }, { "message": "string" }] },
            { "contains": [{ "fieldName": "string" }, { "message": "string" }, { "value": "string" }] },
            { "creditCard": [{ "creditCardTypes": "string[]" }, { "message": "string" }, { "conditionalExpression": "string" }] },
            { "dataUri": [{ "message": "string" }, { "conditionalExpression": "string" }] },
            { "different": [{ "fieldName": "string" }, { "message": "string" }] },
            { "digit": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "email": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "endsWith": [{ "value": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "even": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "extension": [{ "extensions": "string[]" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "factor": [{ "dividend": "number" }, { "fieldName": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "file": [{ "maxFiles": "number" }, { "minFiles": "number" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "fileSize": [{ "maxSize": "number" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "greaterThanEqualTo": [{ "fieldName": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "greaterThan": [{ "fieldName": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "hexColor": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "ip": [{ "version": "IpVersion" }, { "isCidr": "boolean" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "image": [{ "maxWidth": "number" }, { "maxHeight": "number" }, { "minWidth": "number" }, { minHeight: "number" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "json": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "latitude": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "latLong": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "leapYear": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "lessThanEqualTo": [{ "fieldName": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "lessThan": [{ "fieldName": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "longitude": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "lowerCase": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "mac": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "maxDate": [{ "value": "string" }, { "fieldName": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "maxLength": [{ "value": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "maxNumber": [{ "value": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "minDate": [{ "fieldName": "string" }, { "value": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "minLength": [{ "value": "number" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "minNumber": [{ "value": "number" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "noneOf": [{ "matchValues": "any[]" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "numeric": [{ "acceptvalue": "NumericValueType" }, { "allowDecimal": "boolean" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "odd": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "oneOf": [{ "matchvalues": "any[]" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "password": [{ "validation": {"PasswordValidation" : [{"digit": "boolean"},{"alphabet": "boolean"},{"contains": "string"}, {"lowerCase": "boolean"},{"upperCase": "boolean"},{"specialCharacter": "boolean"},{"minLength": "number"},{"maxLength": "number"} ]}}, { "message": "string" }] },
            { "pattern": [{ "expression": "string" }, { "message": "string" }] },
            { "port": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "primeNumber": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "range": [{ "conditionalExpression": "string" }, { "minimumNumber": "string" }, { "maximumNumber": "string" }, { "message": "string" }] },
            { "required": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "startsWith": [{ "value": "string" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "time": [{ "allowSeconds": "boolean" }, { "conditionalExpression": "string" }, { "message": "string" }] },
            { "unique": [{ "message": "string" }] },
            { "upperCase": [{ "conditionalExpression": "string" }, { "message": "string" }] },
            { "url": [{ "conditionalExpression": "string" }, { "message": "string" }] }
        ])
        };
}
