coverage:
  parsers:
    javascript:
      enable_partials: yes
  status:
    project:
      default:
        target: "85%"
    patch:
      enabled: false
  ignore: 
   - "rxweb.io"
   - "docs"
   - "src"
  comment: false
     
